apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: agc-entbannung
  namespace: agc
spec:
  podMetricsEndpoints:
    - port: http-metrics
      scheme: http
      path: /metrics
      interval: 15s
  podTargetLabels:
    - app
  selector:
    matchLabels:
      app: agc-entbannung
